language: python
install:
  - pip install tox 
  - pip install python-coveralls
script:
  - tox
env:
  - TOXENV: py34
after_success:
    coveralls --config_file humantrafficking_tips/.coveragerc --data_file humantrafficking_tips/.coverage
